defaultContentLanguage: en
theme: cupper

params:
  logoAlt: RHVoice
  dateFormat: 2.01.2006
  footer: Â© 2023 RHVoice, [GitHub](https://github.com/RHVoice), rhvoice@rhvoice.org
  urls:
    lp:
      mk: "https://louderpages.org/kiko"
      pt: "https://louderpages.org/leticia"
      sq: "https://louderpages.org/hana"
      tk: "https://louderpages.org/dunya"
      ne: "https://louderpages.org/dina"
      vi: "https://louderpages.org/vi-vu"
      tn: "https://louderpages.org/dimpho"
    pl: https://zlotowicz.pl/synteza
    sk: https://hlas.ondrosik.sk/

languages:
  en:
    baseURL: https://rhvoice.org
    title: RHVoice.org
    languageName: en
    weight: 1
    contentDir: content/en
  ru:
    baseURL: https://rhvoice.ru
    title: RHVoice.ru
    languageName: ru
    weight: 2
    contentDir: content/ru
